server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: inspecticmp
          uri: http://localhost:8082
          predicates:
            - Path=/icmpData/**, 
        - id: registration
          uri: http://localhost:8083
          predicates:
            - Path=/inputInfos/**, 
        - id: inspecthttp
          uri: http://localhost:8084
          predicates:
            - Path=/httpData/**, 
        - id: inspectdns
          uri: http://localhost:8085
          predicates:
            - Path=/dnsData/**, 
        - id: management
          uri: http://localhost:8086
          predicates:
            - Path=/clients/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: inspecticmp
          uri: http://inspecticmp:8080
          predicates:
            - Path=/icmpData/**, 
        - id: registration
          uri: http://registration:8080
          predicates:
            - Path=/inputInfos/**, 
        - id: inspecthttp
          uri: http://inspecthttp:8080
          predicates:
            - Path=/httpData/**, 
        - id: inspectdns
          uri: http://inspectdns:8080
          predicates:
            - Path=/dnsData/**, 
        - id: management
          uri: http://management:8080
          predicates:
            - Path=/clients/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
